<?php
// Auto-generiert – ACF-Felder für Block digirelation/landingpage.
if ( ! defined('ABSPATH') ) exit;
add_action('acf/init', function () {
	if ( ! function_exists('acf_add_local_field_group') ) return;
	acf_add_local_field_group(array(
		'key' => 'group_digi_lp',
		'title' => 'Performance Landingpage',
		'fields' => array(
			array(
				'key' => 'field_dlp_001_tab',
				'label' => 'Allgemein',
				'type' => 'tab',
				'placement' => 'top',
			),
			array(
				'key' => 'field_dlp_002_brand',
				'label' => 'Marken-/Logo-Text',
				'name' => 'brand',
				'type' => 'text',
				'default_value' => 'digirelation',
			),
			array(
				'key' => 'field_dlp_003_cta_url',
				'label' => 'CTA-Link',
				'name' => 'cta_url',
				'type' => 'text',
				'default_value' => '/kontakt/',
			),
			array(
				'key' => 'field_dlp_004_cta_btn',
				'label' => 'CTA-Button Text',
				'name' => 'cta_btn',
				'type' => 'text',
				'default_value' => 'Strategiegespräch anfragen',
			),
			array(
				'key' => 'field_dlp_005_vsl_embed',
				'label' => 'VSL Video-Embed (iframe/video)',
				'name' => 'vsl_embed',
				'type' => 'textarea',
				'default_value' => '',
				'rows' => 3,
				'new_lines' => '',
			),
			array(
				'key' => 'field_dlp_102_vsl_url',
				'label' => 'Video-URL (YouTube/Vimeo)',
				'name' => 'vsl_url',
				'type' => 'text',
				'instructions' => 'YouTube- oder Vimeo-Link. Wird automatisch eingebettet. Hat Vorrang vor dem Embed-Code unten.',
				'default_value' => '',
			),
			array(
				'key' => 'field_dlp_006_vsl_badge',
				'label' => 'Video-Badge Text',
				'name' => 'vsl_badge',
				'type' => 'text',
				'default_value' => 'In 90 Sek. erklärt',
			),
			array(
				'key' => 'field_dlp_007_google_rating',
				'label' => 'Google Bewertung',
				'name' => 'google_rating',
				'type' => 'text',
				'default_value' => '4,9',
			),
			array(
				'key' => 'field_dlp_008_google_reviews',
				'label' => 'Anzahl Google-Bewertungen',
				'name' => 'google_reviews',
				'type' => 'text',
			),
			array(
				'key' => 'field_dlp_104_grw_id',
				'label' => 'Google Reviews Widget ID',
				'name' => 'grw_id',
				'type' => 'text',
				'instructions' => 'ID aus [grw id="X"] — z.B. 1101. Widget wird automatisch ausgeblendet und liest Rating + Anzahl aus.',
				'default_value' => '',
			),
			array(
				'key' => 'field_dlp_103_google_link',
				'label' => 'Google Business Link',
				'name' => 'google_link',
				'type' => 'text',
				'instructions' => 'Link zur Google-Bewertungsseite (macht das Badge klickbar).',
				'default_value' => '',
			),
			array(
				'key' => 'field_dlp_009_tab',
				'label' => 'Hero',
				'type' => 'tab',
				'placement' => 'top',
			),
			array(
				'key' => 'field_dlp_010_hero_eyebrow',
				'label' => 'Eyebrow',
				'name' => 'hero_eyebrow',
				'type' => 'text',
				'default_value' => 'Webdesign mit Performance-Fokus',
			),
			array(
				'key' => 'field_dlp_011_hero_h1a',
				'label' => 'H1 – Teil 1',
				'name' => 'hero_h1a',
				'type' => 'text',
				'default_value' => 'Deine ',
			),
			array(
				'key' => 'field_dlp_012_hero_h1b',
				'label' => 'H1 – farbiges Wort',
				'name' => 'hero_h1b',
				'type' => 'text',
				'default_value' => 'neue Website',
			),
			array(
				'key' => 'field_dlp_013_hero_h1c',
				'label' => 'H1 – Teil 2',
				'name' => 'hero_h1c',
				'type' => 'text',
				'default_value' => ', gebaut für dein Geschäft',
			),
			array(
				'key' => 'field_dlp_014_hero_sub',
				'label' => 'Subtext',
				'name' => 'hero_sub',
				'type' => 'textarea',
				'default_value' => 'Wir bauen dir eine Website, die modern aussieht und zu dem passt, was du wirklich machst. Deine alte hat ausgedient.',
				'rows' => 3,
				'new_lines' => '',
			),
			array(
				'key' => 'field_dlp_017_kpis',
				'label' => 'KPIs (Zahlen-Leiste)',
				'name' => 'kpis',
				'type' => 'repeater',
				'layout' => 'block',
				'collapsed' => 'field_dlp_016_label',
				'button_label' => 'KPI hinzufügen',
				'sub_fields' => array(
					array(
						'key' => 'field_dlp_015_value',
						'label' => 'Wert',
						'name' => 'value',
						'type' => 'text',
					),
					array(
						'key' => 'field_dlp_016_label',
						'label' => 'Label',
						'name' => 'label',
						'type' => 'text',
					),
				),
			),
			array(
				'key' => 'field_dlp_018_tab',
				'label' => 'Problem',
				'type' => 'tab',
				'placement' => 'top',
			),
			array(
				'key' => 'field_dlp_019_problem_eyebrow',
				'label' => 'Eyebrow',
				'name' => 'problem_eyebrow',
				'type' => 'text',
				'default_value' => 'Das Problem',
			),
			array(
				'key' => 'field_dlp_020_problem_h2',
				'label' => 'Überschrift',
				'name' => 'problem_h2',
				'type' => 'text',
				'default_value' => 'Kommt dir das bekannt vor?',
			),
			array(
				'key' => 'field_dlp_021_problem_intro',
				'label' => 'Intro',
				'name' => 'problem_intro',
				'type' => 'textarea',
				'default_value' => 'Drei Probleme, an denen die meisten Websites scheitern. Wahrscheinlich kennst du mindestens eins.',
				'rows' => 3,
				'new_lines' => '',
			),
			array(
				'key' => 'field_dlp_025_problem_cards',
				'label' => 'Problem-Karten',
				'name' => 'problem_cards',
				'type' => 'repeater',
				'layout' => 'block',
				'collapsed' => 'field_dlp_023_title',
				'button_label' => 'Karte hinzufügen',
				'sub_fields' => array(
					array(
						'key' => 'field_dlp_022_icon',
						'label' => 'Icon',
						'name' => 'icon',
						'type' => 'select',
						'default_value' => 'chart',
						'choices' => array(
							'chart' => 'Diagramm (fallend)',
							'screen' => 'Bildschirm',
							'circle-x' => 'Kreis (X)',
							'target' => 'Ziel',
							'bolt' => 'Blitz',
							'shield' => 'Schild',
							'info' => 'Info',
							'monitor' => 'Monitor',
							'search' => 'Lupe',
							'rocket' => 'Rakete',
							'star' => 'Stern',
							'heart' => 'Herz',
							'clock' => 'Uhr',
							'users' => 'Personen',
						),
						'ui' => 1,
						'return_format' => 'value',
						'allow_null' => 0,
					),
					array(
						'key' => 'field_dlp_023_title',
						'label' => 'Titel',
						'name' => 'title',
						'type' => 'text',
					),
					array(
						'key' => 'field_dlp_024_text',
						'label' => 'Text',
						'name' => 'text',
						'type' => 'textarea',
						'default_value' => '',
						'rows' => 3,
						'new_lines' => '',
					),
				),
			),
			array(
				'key' => 'field_dlp_026_tab',
				'label' => 'Lösung',
				'type' => 'tab',
				'placement' => 'top',
			),
			array(
				'key' => 'field_dlp_027_sol_eyebrow',
				'label' => 'Eyebrow',
				'name' => 'sol_eyebrow',
				'type' => 'text',
				'default_value' => 'Die Lösung',
			),
			array(
				'key' => 'field_dlp_028_sol_h2',
				'label' => 'Überschrift',
				'name' => 'sol_h2',
				'type' => 'text',
				'default_value' => 'Deine Website arbeitet endlich für dich',
			),
			array(
				'key' => 'field_dlp_029_sol_intro',
				'label' => 'Intro',
				'name' => 'sol_intro',
				'type' => 'textarea',
				'default_value' => 'Deine Seite bekommt einen Plan, der zu deinem Geschäft passt. Fertig ist sie erst, wenn sie dir Anfragen bringt.',
				'rows' => 3,
				'new_lines' => '',
			),
			array(
				'key' => 'field_dlp_034_solution_cards',
				'label' => 'Lösungs-Karten',
				'name' => 'solution_cards',
				'type' => 'repeater',
				'layout' => 'block',
				'collapsed' => 'field_dlp_031_title',
				'button_label' => 'Karte hinzufügen',
				'sub_fields' => array(
					array(
						'key' => 'field_dlp_030_icon',
						'label' => 'Icon',
						'name' => 'icon',
						'type' => 'select',
						'default_value' => 'target',
						'choices' => array(
							'chart' => 'Diagramm (fallend)',
							'screen' => 'Bildschirm',
							'circle-x' => 'Kreis (X)',
							'target' => 'Ziel',
							'bolt' => 'Blitz',
							'shield' => 'Schild',
							'info' => 'Info',
							'monitor' => 'Monitor',
							'search' => 'Lupe',
							'rocket' => 'Rakete',
							'star' => 'Stern',
							'heart' => 'Herz',
							'clock' => 'Uhr',
							'users' => 'Personen',
						),
						'ui' => 1,
						'return_format' => 'value',
						'allow_null' => 0,
					),
					array(
						'key' => 'field_dlp_031_title',
						'label' => 'Titel',
						'name' => 'title',
						'type' => 'text',
					),
					array(
						'key' => 'field_dlp_032_text',
						'label' => 'Text',
						'name' => 'text',
						'type' => 'textarea',
						'default_value' => '',
						'rows' => 3,
						'new_lines' => '',
					),
					array(
						'key' => 'field_dlp_033_checks',
						'label' => 'Häkchen-Liste (1 pro Zeile)',
						'name' => 'checks',
						'type' => 'textarea',
						'default_value' => '',
						'rows' => 3,
						'new_lines' => '',
					),
				),
			),
			array(
				'key' => 'field_dlp_035_tab',
				'label' => 'Vergleich',
				'type' => 'tab',
				'placement' => 'top',
			),
			array(
				'key' => 'field_dlp_036_cmp_eyebrow',
				'label' => 'Eyebrow',
				'name' => 'cmp_eyebrow',
				'type' => 'text',
				'default_value' => 'Der Unterschied',
			),
			array(
				'key' => 'field_dlp_037_cmp_h2',
				'label' => 'Überschrift',
				'name' => 'cmp_h2',
				'type' => 'text',
				'default_value' => 'Baukasten, Agentur oder digirelation?',
			),
			array(
				'key' => 'field_dlp_038_cmp_intro',
				'label' => 'Intro',
				'name' => 'cmp_intro',
				'type' => 'textarea',
				'default_value' => 'Worin sich eine Website von uns von den üblichen Wegen unterscheidet.',
				'rows' => 3,
				'new_lines' => '',
			),
			array(
				'key' => 'field_dlp_039_cmp_crit_label',
				'label' => 'Spalte: Kriterium',
				'name' => 'cmp_crit_label',
				'type' => 'text',
				'default_value' => 'Was zählt',
			),
			array(
				'key' => 'field_dlp_040_cmp_col1',
				'label' => 'Spalte 1 Titel',
				'name' => 'cmp_col1',
				'type' => 'text',
				'default_value' => 'Website-Baukasten',
			),
			array(
				'key' => 'field_dlp_041_cmp_col2',
				'label' => 'Spalte 2 Titel',
				'name' => 'cmp_col2',
				'type' => 'text',
				'default_value' => 'Klassische Agentur',
			),
			array(
				'key' => 'field_dlp_042_cmp_col3',
				'label' => 'Spalte 3 Titel (digirelation)',
				'name' => 'cmp_col3',
				'type' => 'text',
				'default_value' => 'digirelation',
			),
			array(
				'key' => 'field_dlp_047_compare_rows',
				'label' => 'Vergleichs-Zeilen',
				'name' => 'compare_rows',
				'type' => 'repeater',
				'layout' => 'block',
				'collapsed' => 'field_dlp_043_crit',
				'button_label' => 'Zeile hinzufügen',
				'sub_fields' => array(
					array(
						'key' => 'field_dlp_043_crit',
						'label' => 'Kriterium',
						'name' => 'crit',
						'type' => 'text',
					),
					array(
						'key' => 'field_dlp_044_c1',
						'label' => 'Spalte 1',
						'name' => 'c1',
						'type' => 'text',
					),
					array(
						'key' => 'field_dlp_045_c2',
						'label' => 'Spalte 2',
						'name' => 'c2',
						'type' => 'text',
					),
					array(
						'key' => 'field_dlp_046_c3',
						'label' => 'Spalte 3 (digirelation)',
						'name' => 'c3',
						'type' => 'text',
					),
				),
			),
			array(
				'key' => 'field_dlp_048_tab',
				'label' => 'Leistungen',
				'type' => 'tab',
				'placement' => 'top',
			),
			array(
				'key' => 'field_dlp_049_feat_h2',
				'label' => 'Überschrift',
				'name' => 'feat_h2',
				'type' => 'text',
				'default_value' => 'Das steckt in deiner neuen Website',
			),
			array(
				'key' => 'field_dlp_050_feat_intro',
				'label' => 'Intro',
				'name' => 'feat_intro',
				'type' => 'textarea',
				'default_value' => 'Deine Seite läuft auf WordPress und ist von Grund auf für Tempo, Handy und Sichtbarkeit gebaut.',
				'rows' => 3,
				'new_lines' => '',
			),
			array(
				'key' => 'field_dlp_051_feat_image',
				'label' => 'Bild (links)',
				'name' => 'feat_image',
				'type' => 'image',
				'return_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array(
				'key' => 'field_dlp_052_feat_accent_icon',
				'label' => 'Akzent-Karte Icon',
				'name' => 'feat_accent_icon',
				'type' => 'select',
				'default_value' => 'info',
				'choices' => array(
					'chart' => 'Diagramm (fallend)',
					'screen' => 'Bildschirm',
					'circle-x' => 'Kreis (X)',
					'target' => 'Ziel',
					'bolt' => 'Blitz',
					'shield' => 'Schild',
					'info' => 'Info',
					'monitor' => 'Monitor',
					'search' => 'Lupe',
					'rocket' => 'Rakete',
					'star' => 'Stern',
					'heart' => 'Herz',
					'clock' => 'Uhr',
					'users' => 'Personen',
				),
				'ui' => 1,
				'return_format' => 'value',
				'allow_null' => 0,
			),
			array(
				'key' => 'field_dlp_053_feat_accent_t',
				'label' => 'Akzent-Karte Titel',
				'name' => 'feat_accent_t',
				'type' => 'text',
				'default_value' => 'Für dein Geschäft gebaut',
			),
			array(
				'key' => 'field_dlp_054_feat_accent_p',
				'label' => 'Akzent-Karte Text',
				'name' => 'feat_accent_p',
				'type' => 'textarea',
				'default_value' => 'Deine Seite entsteht neu für dein Geschäft und deinen Verkauf, statt fertig aus dem Baukasten zu kommen.',
				'rows' => 3,
				'new_lines' => '',
			),
			array(
				'key' => 'field_dlp_055_feat_tech_icon',
				'label' => 'Technik-Karte Icon',
				'name' => 'feat_tech_icon',
				'type' => 'select',
				'default_value' => 'monitor',
				'choices' => array(
					'chart' => 'Diagramm (fallend)',
					'screen' => 'Bildschirm',
					'circle-x' => 'Kreis (X)',
					'target' => 'Ziel',
					'bolt' => 'Blitz',
					'shield' => 'Schild',
					'info' => 'Info',
					'monitor' => 'Monitor',
					'search' => 'Lupe',
					'rocket' => 'Rakete',
					'star' => 'Stern',
					'heart' => 'Herz',
					'clock' => 'Uhr',
					'users' => 'Personen',
				),
				'ui' => 1,
				'return_format' => 'value',
				'allow_null' => 0,
			),
			array(
				'key' => 'field_dlp_056_feat_tech_t',
				'label' => 'Technik-Karte Titel',
				'name' => 'feat_tech_t',
				'type' => 'text',
				'default_value' => 'Technik, die mitwächst',
			),
			array(
				'key' => 'field_dlp_057_feat_tech_list',
				'label' => 'Technik-Karte Liste (1 pro Zeile)',
				'name' => 'feat_tech_list',
				'type' => 'textarea',
				'default_value' => 'Responsive auf Handy, Tablet und Desktop
Schnelle Ladezeiten, auch mit vielen Bildern',
				'rows' => 3,
				'new_lines' => '',
			),
			array(
				'key' => 'field_dlp_058_feat_find_icon',
				'label' => 'Sichtbarkeit-Karte Icon',
				'name' => 'feat_find_icon',
				'type' => 'select',
				'default_value' => 'search',
				'choices' => array(
					'chart' => 'Diagramm (fallend)',
					'screen' => 'Bildschirm',
					'circle-x' => 'Kreis (X)',
					'target' => 'Ziel',
					'bolt' => 'Blitz',
					'shield' => 'Schild',
					'info' => 'Info',
					'monitor' => 'Monitor',
					'search' => 'Lupe',
					'rocket' => 'Rakete',
					'star' => 'Stern',
					'heart' => 'Herz',
					'clock' => 'Uhr',
					'users' => 'Personen',
				),
				'ui' => 1,
				'return_format' => 'value',
				'allow_null' => 0,
			),
			array(
				'key' => 'field_dlp_059_feat_find_t',
				'label' => 'Sichtbarkeit-Karte Titel',
				'name' => 'feat_find_t',
				'type' => 'text',
				'default_value' => 'Gefunden werden',
			),
			array(
				'key' => 'field_dlp_060_feat_find_list',
				'label' => 'Sichtbarkeit-Karte Liste (1 pro Zeile)',
				'name' => 'feat_find_list',
				'type' => 'textarea',
				'default_value' => 'SEO-Grundlagen von Anfang an
Sauberer, schneller Code
DSGVO-konform aufgesetzt',
				'rows' => 3,
				'new_lines' => '',
			),
			array(
				'key' => 'field_dlp_061_tab',
				'label' => 'Ablauf',
				'type' => 'tab',
				'placement' => 'top',
			),
			array(
				'key' => 'field_dlp_062_how_eyebrow',
				'label' => 'Eyebrow',
				'name' => 'how_eyebrow',
				'type' => 'text',
				'default_value' => 'So läuft es ab',
			),
			array(
				'key' => 'field_dlp_063_how_h2',
				'label' => 'Überschrift',
				'name' => 'how_h2',
				'type' => 'text',
				'default_value' => 'So entsteht deine neue Website',
			),
			array(
				'key' => 'field_dlp_064_how_intro',
				'label' => 'Intro',
				'name' => 'how_intro',
				'type' => 'textarea',
				'default_value' => 'Vier Schritte, klar und ohne Überraschungen. Du weißt jederzeit, woran wir gerade arbeiten.',
				'rows' => 3,
				'new_lines' => '',
			),
			array(
				'key' => 'field_dlp_065_how_image',
				'label' => 'Banner-Bild',
				'name' => 'how_image',
				'type' => 'image',
				'return_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array(
				'key' => 'field_dlp_068_steps',
				'label' => 'Schritte (automatisch nummeriert)',
				'name' => 'steps',
				'type' => 'repeater',
				'layout' => 'block',
				'collapsed' => 'field_dlp_066_title',
				'button_label' => 'Schritt hinzufügen',
				'sub_fields' => array(
					array(
						'key' => 'field_dlp_066_title',
						'label' => 'Titel',
						'name' => 'title',
						'type' => 'text',
					),
					array(
						'key' => 'field_dlp_067_text',
						'label' => 'Text',
						'name' => 'text',
						'type' => 'textarea',
						'default_value' => '',
						'rows' => 3,
						'new_lines' => '',
					),
				),
			),
			array(
				'key' => 'field_dlp_069_tab',
				'label' => 'Referenzen',
				'type' => 'tab',
				'placement' => 'top',
			),
			array(
				'key' => 'field_dlp_070_ref_eyebrow',
				'label' => 'Eyebrow',
				'name' => 'ref_eyebrow',
				'type' => 'text',
				'default_value' => 'Referenzen',
			),
			array(
				'key' => 'field_dlp_071_ref_h2',
				'label' => 'Überschrift',
				'name' => 'ref_h2',
				'type' => 'text',
				'default_value' => 'Echte Projekte aus 12 Branchen',
			),
			array(
				'key' => 'field_dlp_072_ref_intro',
				'label' => 'Intro',
				'name' => 'ref_intro',
				'type' => 'textarea',
				'default_value' => 'Ein Auszug aus über 100 Projekten in 6 Ländern. Die Bandbreite reicht vom Energieberater bis zum Premium-Gin.',
				'rows' => 3,
				'new_lines' => '',
			),
			array(
				'key' => 'field_dlp_077_references',
				'label' => 'Referenz-Karten',
				'name' => 'references',
				'type' => 'repeater',
				'layout' => 'block',
				'collapsed' => 'field_dlp_074_name',
				'button_label' => 'Referenz hinzufügen',
				'sub_fields' => array(
					array(
						'key' => 'field_dlp_073_image',
						'label' => 'Bild',
						'name' => 'image',
						'type' => 'image',
						'return_format' => 'url',
						'preview_size' => 'medium',
						'library' => 'all',
					),
					array(
						'key' => 'field_dlp_074_name',
						'label' => 'Name',
						'name' => 'name',
						'type' => 'text',
					),
					array(
						'key' => 'field_dlp_075_branche',
						'label' => 'Branche',
						'name' => 'branche',
						'type' => 'text',
					),
					array(
						'key' => 'field_dlp_076_geo',
						'label' => 'Ort',
						'name' => 'geo',
						'type' => 'text',
					),
				),
			),
			array(
				'key' => 'field_dlp_078_tab',
				'label' => 'Kundenstimmen',
				'type' => 'tab',
				'placement' => 'top',
			),
			array(
				'key' => 'field_dlp_079_proof_eyebrow',
				'label' => 'Eyebrow',
				'name' => 'proof_eyebrow',
				'type' => 'text',
				'default_value' => 'Kundenstimmen',
			),
			array(
				'key' => 'field_dlp_080_proof_h2',
				'label' => 'Überschrift',
				'name' => 'proof_h2',
				'type' => 'text',
				'default_value' => 'Was Kunden über uns sagen',
			),
			array(
				'key' => 'field_dlp_084_testimonials',
				'label' => 'Testimonials',
				'name' => 'testimonials',
				'type' => 'repeater',
				'layout' => 'block',
				'collapsed' => 'field_dlp_082_name',
				'button_label' => 'Testimonial hinzufügen',
				'sub_fields' => array(
					array(
						'key' => 'field_dlp_081_quote',
						'label' => 'Zitat',
						'name' => 'quote',
						'type' => 'textarea',
						'default_value' => '',
						'rows' => 3,
						'new_lines' => '',
					),
					array(
						'key' => 'field_dlp_082_name',
						'label' => 'Name',
						'name' => 'name',
						'type' => 'text',
					),
					array(
						'key' => 'field_dlp_083_firma',
						'label' => 'Firma',
						'name' => 'firma',
						'type' => 'text',
					),
				),
			),
			array(
				'key' => 'field_dlp_085_logos_title',
				'label' => 'Logo-Leiste Text',
				'name' => 'logos_title',
				'type' => 'text',
				'default_value' => 'Vertraut von Unternehmen in 6 Ländern',
			),
			array(
				'key' => 'field_dlp_087_logos',
				'label' => 'Logo-Leiste (Namen)',
				'name' => 'logos',
				'type' => 'repeater',
				'layout' => 'block',
				'collapsed' => 'field_dlp_086_name',
				'button_label' => 'Logo hinzufügen',
				'sub_fields' => array(
					array(
						'key' => 'field_dlp_086_name',
						'label' => 'Name',
						'name' => 'name',
						'type' => 'text',
					),
				),
			),
			array(
				'key' => 'field_dlp_088_tab',
				'label' => 'FAQ',
				'type' => 'tab',
				'placement' => 'top',
			),
			array(
				'key' => 'field_dlp_089_faq_eyebrow',
				'label' => 'Eyebrow',
				'name' => 'faq_eyebrow',
				'type' => 'text',
				'default_value' => 'Häufige Fragen',
			),
			array(
				'key' => 'field_dlp_090_faq_h2',
				'label' => 'Überschrift',
				'name' => 'faq_h2',
				'type' => 'text',
				'default_value' => 'Was du dich vor dem Start fragst',
			),
			array(
				'key' => 'field_dlp_093_faqs',
				'label' => 'FAQ',
				'name' => 'faqs',
				'type' => 'repeater',
				'layout' => 'block',
				'collapsed' => 'field_dlp_091_frage',
				'button_label' => 'Frage hinzufügen',
				'sub_fields' => array(
					array(
						'key' => 'field_dlp_091_frage',
						'label' => 'Frage',
						'name' => 'frage',
						'type' => 'text',
					),
					array(
						'key' => 'field_dlp_092_antwort',
						'label' => 'Antwort',
						'name' => 'antwort',
						'type' => 'textarea',
						'default_value' => '',
						'rows' => 3,
						'new_lines' => '',
					),
				),
			),
			array(
				'key' => 'field_dlp_094_tab',
				'label' => 'CTA',
				'type' => 'tab',
				'placement' => 'top',
			),
			array(
				'key' => 'field_dlp_095_cta_eyebrow',
				'label' => 'Eyebrow',
				'name' => 'cta_eyebrow',
				'type' => 'text',
				'default_value' => 'Strategiegespräch',
			),
			array(
				'key' => 'field_dlp_096_cta_h2',
				'label' => 'Überschrift',
				'name' => 'cta_h2',
				'type' => 'text',
				'default_value' => 'Finde heraus, warum deine Website keine Anfragen bringt',
			),
			array(
				'key' => 'field_dlp_097_cta_p',
				'label' => 'Text',
				'name' => 'cta_p',
				'type' => 'textarea',
				'default_value' => 'Erzähl uns von deiner aktuellen Seite und deinem Ziel. Im Strategiegespräch bekommst du eine ehrliche Einschätzung, woran es liegt und was sich zuerst lohnt.',
				'rows' => 3,
				'new_lines' => '',
			),
			array(
				'key' => 'field_dlp_098_cta_checks',
				'label' => 'Häkchen-Liste (1 pro Zeile)',
				'name' => 'cta_checks',
				'type' => 'textarea',
				'default_value' => 'Konkrete Schwachstellen statt allgemeiner Tipps
Ein klarer Plan für die neue Website
Unverbindlich, mit Antwort in 24 Stunden',
				'rows' => 3,
				'new_lines' => '',
			),
			array(
				'key' => 'field_dlp_099_cta_foot',
				'label' => 'Fußnote',
				'name' => 'cta_foot',
				'type' => 'text',
				'default_value' => 'Unverbindlich und keine Akquise-Anrufe ohne deine Zustimmung',
			),
			array(
				'key' => 'field_dlp_100_tab',
				'label' => 'Footer',
				'type' => 'tab',
				'placement' => 'top',
			),
			array(
				'key' => 'field_dlp_101_footer_copy',
				'label' => 'Copyright',
				'name' => 'footer_copy',
				'type' => 'text',
				'default_value' => '© 2026 digirelation. Webdesign mit Performance-Fokus.',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'digirelation/landingpage',
				),
			),
		),
		'menu_order' => 0,
		'active' => true,
	));

	acf_add_local_field_group(array(
		'key' => 'group_digi_contact',
		'title' => 'Kontaktseite – Inhalte',
		'fields' => array(
			array(
				'key' => 'field_dlc_001_lp_url',
				'label' => 'Link zur Landingpage (Zurück-Button)',
				'name' => 'contact_lp_url',
				'type' => 'text',
				'default_value' => '/performance-landingpage/',
			),
			array(
				'key' => 'field_dlc_002_eyebrow',
				'label' => 'Eyebrow',
				'name' => 'contact_eyebrow',
				'type' => 'text',
				'default_value' => 'Strategiegespräch',
			),
			array(
				'key' => 'field_dlc_003_h1',
				'label' => 'Überschrift',
				'name' => 'contact_h1',
				'type' => 'text',
				'default_value' => 'Finde heraus, warum deine Website keine Anfragen bringt',
			),
			array(
				'key' => 'field_dlc_004_sub',
				'label' => 'Subtext',
				'name' => 'contact_sub',
				'type' => 'textarea',
				'default_value' => 'Erzähl uns von deiner aktuellen Seite und deinem Ziel. Im Strategiegespräch bekommst du eine ehrliche Einschätzung, woran es liegt und was sich zuerst lohnt.',
				'rows' => 3,
				'new_lines' => '',
			),
			array(
				'key' => 'field_dlc_005_values',
				'label' => 'Vorteile (Häkchen-Liste)',
				'name' => 'contact_values',
				'type' => 'repeater',
				'layout' => 'block',
				'button_label' => 'Punkt hinzufügen',
				'sub_fields' => array(
					array(
						'key' => 'field_dlc_005a_bold',
						'label' => 'Fett-Text',
						'name' => 'bold',
						'type' => 'text',
					),
					array(
						'key' => 'field_dlc_005b_text',
						'label' => 'Rest des Texts',
						'name' => 'text',
						'type' => 'text',
					),
				),
			),
			array(
				'key' => 'field_dlc_006_g_rating',
				'label' => 'Google Bewertung',
				'name' => 'contact_google_rating',
				'type' => 'text',
				'default_value' => '4,9',
			),
			array(
				'key' => 'field_dlc_007_g_reviews',
				'label' => 'Anzahl Google-Bewertungen',
				'name' => 'contact_google_reviews',
				'type' => 'text',
				'default_value' => '',
			),
			array(
				'key' => 'field_dlc_008_g_link',
				'label' => 'Google Business Link',
				'name' => 'contact_google_link',
				'type' => 'text',
				'instructions' => 'Link zur Google-Bewertungsseite.',
				'default_value' => '',
			),
			array(
				'key' => 'field_dlc_009_form_h2',
				'label' => 'Formular-Titel',
				'name' => 'contact_form_h2',
				'type' => 'text',
				'default_value' => 'Strategiegespräch anfragen',
			),
			array(
				'key' => 'field_dlc_010_form_sub',
				'label' => 'Formular-Subtext',
				'name' => 'contact_form_sub',
				'type' => 'text',
				'default_value' => 'Trag deine Daten ein. Wir melden uns innerhalb von 24 Stunden.',
			),
			array(
				'key' => 'field_dlc_011_submit',
				'label' => 'Absenden-Button',
				'name' => 'contact_submit',
				'type' => 'text',
				'default_value' => 'Strategiegespräch anfragen',
			),
			array(
				'key' => 'field_dlc_012_foot',
				'label' => 'Fußnote unter Button',
				'name' => 'contact_foot',
				'type' => 'text',
				'default_value' => 'Unverbindlich und keine Akquise-Anrufe ohne deine Zustimmung',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page',
					'operator' => '==',
					'value' => '1055',
				),
			),
		),
		'menu_order' => 0,
		'active' => true,
	));

	acf_add_local_field_group(array(
		'key'    => 'group_digi_thanks',
		'title'  => 'Danke-Seite – Inhalte',
		'fields' => array(

			// ── Tab: Allgemein ──────────────────────────────────────────
			array( 'key' => 'field_dlt_t1', 'label' => 'Allgemein', 'type' => 'tab', 'placement' => 'top' ),
			array(
				'key'           => 'field_dlt_lp_url',
				'label'         => 'Zurück-Link (zur Landingpage)',
				'name'          => 'thanks_lp_url',
				'type'          => 'text',
				'default_value' => '/performance-landingpage/',
			),
			array(
				'key'           => 'field_dlt_confirm',
				'label'         => 'Bestätigungs-Badge Text',
				'name'          => 'thanks_confirm',
				'type'          => 'text',
				'default_value' => 'Deine Anfrage ist eingegangen',
			),

			// ── Tab: Inhalt ──────────────────────────────────────────────
			array( 'key' => 'field_dlt_t2', 'label' => 'Inhalt', 'type' => 'tab', 'placement' => 'top' ),
			array(
				'key'           => 'field_dlt_eyebrow',
				'label'         => 'Eyebrow',
				'name'          => 'thanks_eyebrow',
				'type'          => 'text',
				'default_value' => 'Letzter Schritt',
			),
			array(
				'key'           => 'field_dlt_h1',
				'label'         => 'Überschrift (H1)',
				'name'          => 'thanks_h1',
				'type'          => 'text',
				'default_value' => 'Sicher dir jetzt deinen Termin mit Fabio',
			),
			array(
				'key'           => 'field_dlt_sub',
				'label'         => 'Subtext',
				'name'          => 'thanks_sub',
				'type'          => 'textarea',
				'rows'          => 4,
				'new_lines'     => '',
				'default_value' => 'Damit du nicht auf einen Rückruf wartest, suchst du dir gleich selbst einen Slot aus. Im Gespräch geht Fabio deine aktuelle Seite mit dir durch. Du erfährst, woran es hängt, und bekommst eine konkrete Strategie, wie du deine Seite sofort besser machst.',
			),
			array(
				'key'        => 'field_dlt_benefits',
				'label'      => 'Vorteile (Liste)',
				'name'       => 'thanks_benefits',
				'type'       => 'repeater',
				'layout'     => 'block',
				'min'        => 1,
				'button_label' => 'Vorteil hinzufügen',
				'sub_fields' => array(
					array(
						'key'           => 'field_dlt_benefit_bold',
						'label'         => 'Fett (Einleitung)',
						'name'          => 'bold',
						'type'          => 'text',
						'default_value' => '',
					),
					array(
						'key'           => 'field_dlt_benefit_rest',
						'label'         => 'Rest des Textes',
						'name'          => 'rest',
						'type'          => 'text',
						'default_value' => '',
					),
				),
			),

			// ── Tab: Host ────────────────────────────────────────────────
			array( 'key' => 'field_dlt_t3', 'label' => 'Host', 'type' => 'tab', 'placement' => 'top' ),
			array(
				'key'           => 'field_dlt_host_name',
				'label'         => 'Name',
				'name'          => 'thanks_host_name',
				'type'          => 'text',
				'default_value' => 'Fabio Scatigna',
			),
			array(
				'key'           => 'field_dlt_host_role',
				'label'         => 'Rolle (kursiv)',
				'name'          => 'thanks_host_role',
				'type'          => 'text',
				'default_value' => 'Key Account & Success',
			),
			array(
				'key'           => 'field_dlt_host_company',
				'label'         => 'Unternehmen',
				'name'          => 'thanks_host_company',
				'type'          => 'text',
				'default_value' => 'digirelation',
			),

			// ── Tab: Termin ──────────────────────────────────────────────
			array( 'key' => 'field_dlt_t4', 'label' => 'Termin-Buchung', 'type' => 'tab', 'placement' => 'top' ),
			array(
				'key'           => 'field_dlt_cal_url',
				'label'         => 'Cal.com / Kalender-URL',
				'name'          => 'thanks_cal_url',
				'type'          => 'text',
				'default_value' => 'https://cal.com/fabio-scatigna-ncbbbr/45min',
			),
			array(
				'key'           => 'field_dlt_book_title',
				'label'         => 'Buchungs-Titel',
				'name'          => 'thanks_book_title',
				'type'          => 'text',
				'default_value' => 'Termin wählen',
			),
			array(
				'key'           => 'field_dlt_book_duration',
				'label'         => 'Dauer-Badge',
				'name'          => 'thanks_book_duration',
				'type'          => 'text',
				'default_value' => '◷ 30 Min',
			),
			array(
				'key'           => 'field_dlt_book_sub',
				'label'         => 'Text unter Titel',
				'name'          => 'thanks_book_sub',
				'type'          => 'text',
				'default_value' => 'Wähl einen Tag und eine Uhrzeit, die dir passen. Den Rest erledigen wir im Gespräch.',
			),
			array(
				'key'           => 'field_dlt_book_btn',
				'label'         => 'Button-Text',
				'name'          => 'thanks_book_btn',
				'type'          => 'text',
				'default_value' => 'Termin mit Fabio buchen',
			),
			array(
				'key'           => 'field_dlt_book_note',
				'label'         => 'Hinweis unter Button',
				'name'          => 'thanks_book_note',
				'type'          => 'text',
				'default_value' => 'Du landest direkt im Kalender und wählst Tag und Uhrzeit, die dir passen.',
			),
			array(
				'key'           => 'field_dlt_book_foot',
				'label'         => 'Fußzeile Buchungsbox',
				'name'          => 'thanks_book_foot',
				'type'          => 'text',
				'default_value' => '✓ Unverbindlich, du kannst den Termin jederzeit verschieben',
			),

			// ── Tab: Trust ───────────────────────────────────────────────
			array( 'key' => 'field_dlt_t5', 'label' => 'Trust', 'type' => 'tab', 'placement' => 'top' ),
			array(
				'key'           => 'field_dlt_google_rating',
				'label'         => 'Google Bewertung',
				'name'          => 'thanks_google_rating',
				'type'          => 'text',
				'default_value' => '4,9 von 5',
			),
			array(
				'key'           => 'field_dlt_kpi1_num',
				'label'         => 'KPI 1 – Zahl',
				'name'          => 'thanks_kpi1_num',
				'type'          => 'text',
				'default_value' => '100+',
			),
			array(
				'key'           => 'field_dlt_kpi1_label',
				'label'         => 'KPI 1 – Bezeichnung',
				'name'          => 'thanks_kpi1_label',
				'type'          => 'text',
				'default_value' => 'Projekte',
			),
			array(
				'key'           => 'field_dlt_kpi2_num',
				'label'         => 'KPI 2 – Zahl',
				'name'          => 'thanks_kpi2_num',
				'type'          => 'text',
				'default_value' => '6',
			),
			array(
				'key'           => 'field_dlt_kpi2_label',
				'label'         => 'KPI 2 – Bezeichnung',
				'name'          => 'thanks_kpi2_label',
				'type'          => 'text',
				'default_value' => 'Länder',
			),
		),
		'location' => array(
			array(
				array(
					'param'    => 'block',
					'operator' => '==',
					'value'    => 'digirelation/thanks',
				),
			),
		),
		'menu_order' => 0,
		'active'     => true,
	));
});
